#!/usr/bin/python3

import sys

class Matrix(object):
    def __init__(self, width=10, height=22):
        self.width = width
        self.height = height
        self.state = [["." for j in range(width)] for i in range(height)]
    def printit(self):
        for row in range(self.height):
            for col in range(self.width):
                print(self.state[row][col], end=" ")
            print()  # plain newline

matrix = Matrix()

while True:
    x = input()

    if x == "q":
        sys.exit(0)

    elif x == "p":
        matrix.printit()
